### ISSUE TITLE
Move questions to correct section

### ISSUE THREAD

**Issue by dkoutsonikolis** [danielsobrado/CCDAK-Exam-Questions#10]
Questions 4,5 & 6 in `/Security/Questions1.md` are about Confluent Schema Registry so I believe they should be moved to `/Schema-Registry`.

**Comment by danielsobrado** [comment]
Yes, makes sense, feel free to submit a PR.

**Comment by dkoutsonikolis** [comment]
Happy to submit a PR, but it looks like I don’t have write access. Could you grant me permissions?
