### ISSUE TITLE
Fix correct answer

### ISSUE THREAD

**Issue by dkoutsonikolis** [danielsobrado/CCDAK-Exam-Questions#11]
I believe the correct answer for Question 1 in `/CLI/Questions1.md` should be B, not A. Here's why:

- In the same question set, Question 7 addresses a similar scenario, suggesting `kafka-configs.sh` as the correct solution.
- The `/CLI/README.md` file explicitly states that kafka-configs.sh is used for modifying broker, **topic**, and client configs, which aligns more closely with option B as the correct answer.

**Comment by danielsobrado** [comment]
Thanks a lot, updated!
