### ISSUE TITLE
KSQL question

### ISSUE THREAD

**Issue by karimrebai** [danielsobrado/CCDAK-Exam-Questions#6]
Hello Daniel,
First thank you for your work, very interesting.
I'm not sure about the answer for question 16 in KSQL section, it's mentioned that we should use the keyword WITHIN to define the duraation of a hopping window.
Isn't SIZE keyword instead ?
Thank you

**Comment by danielsobrado** [comment]
Yes, you are right, I updated it.

Thanks a lot!
