### ISSUE TITLE
Incorrect questions in KSQL section

### ISSUE THREAD

**Issue by abrekken** [danielsobrado/CCDAK-Exam-Questions#8]
Please take this as constructive, but I think it would help if you included links to documentation on your answers as there seems to be a number of inaccuracies in the ksql questions.  Some examples I noticed:

**Question 17:** 
- INNER JOIN is correct.. In fact I'm not sure "JOIN" is even a valid option in Ksql? 
- Additionally, this question is misleading because a stream to stream join requires windowing, which none of your answers indicate.  

**Questions 24 and 30**
- These are duplicates, but 24 is the one to remove because "REPARTITION" isn't even a keyword.

**Question 27**
- Default retention is 7 days, not 1 day.

**Comment by danielsobrado** [comment]
Thanks so much, I made the changes, let me know if you find any other issue.

Of course is constructive, with those improvements and your help  the repo is more useful!
