### ISSUE TITLE
Fix answer explanation [Broker] [Questions1 -> Question 3]

### ISSUE THREAD

**Issue by dkoutsonikolis** [danielsobrado/CCDAK-Exam-Questions#9]
In Brokers -> Questions1 -> Question 3 -> Explanation for 2. ([link](https://github.com/danielsobrado/CCDAK-Exam-Questions/blob/main/Broker/Questions1.md?plain=1#L79)) it is mentioned:

`Kafka uses Zookeeper to manage cluster metadata and to perform leader election for both the controller and partition leaders.`

which I think is wrong and should be changed to

`Kafka uses Zookeeper to manage cluster metadata and to perform leader election for the controller.`

As mentioned already in the next explanation, the Controller manages partition leader elections, not Zookeeper.

**Comment by danielsobrado** [comment]
Thanks a lot, updated!

**Comment by dkoutsonikolis** [comment]
Thank you for this repo!
